### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by clibequilibrium** [nikp123/x-watcher#1]
Hello @nikp123  

Thank you for publishing this repo. I found it very useful in my Game Engine for hot reloading shaders.
Question for you, would you be adding a permissive LICENSE? 

EDIT: 

nvm found it in Readme 😁

**Comment by nikp123** [comment]
nice to see it being actually used outside my own projects

you're obviously very welcome to use it in any shape or form you like

just be aware that macOS support is missing, that could be one major caveat
